### ISSUE TITLE
Push Notifications via Google/Chrome

### ISSUE THREAD

**Issue by darkforcesjedi** [seikur0/PGO-mapscan-opt#106]
https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web

Any thoughts on implementing this? This would enable push notifications (in Android at least, I don't know about iOS) without requiring pushbullet.

**Comment by seikur0** [comment]
I took that out of your pull, because I want to rely on PokeAlarm for notifications in the future. And doing these notifications with the browser doesn't seem like the ideal solution to me. Also I need to rework the website-tool communication and after that the website won't have all the informations anymore either way.

**Comment by seikur0** [comment]
Telegram support added.
