### ISSUE TITLE
Do you scan each spawn point individually or combine them?

### ISSUE THREAD

**Issue by plebcity** [seikur0/PGO-mapscan-opt#131]
An improvement would be that you combine different spawn points into 1 scan and create some kind of areas so bots don't travel that much and get less bans.

**Comment by seikur0** [comment]
I can't even remember the last ban I had. By combining points, I would scan some points later than I could and would lose time to get there (to that Snorlax maybe :) ).

**Comment by plebcity** [comment]
@seikur0 Do you keep track of what pokemon spawn at which spawn point somewhere? I would like to write something like that to a database so I can query the spawns and do some more research on different biome's

**Comment by seikur0** [comment]
The data is stored by the tool and it also contains the spawn id, so you can easily do that.

**Comment by plebcity** [comment]
I'ill check when I get home and start making a database output.

**Comment by darkforcesjedi** [comment]
Everything you need for spawn analysis is in the spawns0 files. I've been working on my own tool to help me find nests based on the data. It will work a lot better if you read all of the spawn events into memory and process them in RAM rather than using a database. Searching for spawn events in a geofenced area (i.e. to see what spawn rates look like in a geographic region) requires querying the data numerous times.

Example where I found a Charmander nest:
http://oi65.tinypic.com/2e58j5t.jpg
