### ISSUE TITLE
New Features for the Map

### ISSUE THREAD

**Issue by Trustmania** [seikur0/PGO-mapscan-opt#138]
Hello,

you did a very nice job! I would like to suggest 3 new Features

1.) The Pokemons on the Map should have a timer under the Pokemon (like http://www2.pic-upload.de/img/31648886/media-20160907.jpg) If the time is over, the timebox should be removed.

2.) In the description of one Pokemon it would be nice, to see when it was detected with which time. To have a manual overview over span spots.

3.) A additional Filter to see all pokemons which are desporned. So it would be nice, to see for example all bisasam's

Best regards,
Sascha

**Comment by seikur0** [comment]
Hey,

I don't like feature 1, it's just clustering up the map and you can already see the timer, when you click the icons.

2 and 3 maybe as separate maps each, like 2 maybe just showing all spawnpoints color coded with the learning file as only input and 3 maybe reading from the log files and putting out a heatmap.

These are not really priorities for me though, you can give it a try though :)

**Comment by Trustmania** [comment]
I see.

I will leave it running over night to get a feeling and tomorrow i will think about, what would be nice.

**Comment by seikur0** [comment]
I'll close this for now, if you do it, make a pull request ;)

**Comment by FrozenSocket** [comment]
When I read this the other day I agreed showing the times would clutter up the map.

But... Today I could really use the feature. I'm sending a screenshot (via IM) of the area to a friend who's walking around catching stuff and it would be so much easier to have the times in the screenshot instead of having to type them all out afterwards so he knows what to get first.

Maybe we could have a toggle for the best of both?

**Comment by Trustmania** [comment]
@FrozenSocket yes this is what i thought. You have one button which gives you all the times under the pokemons and you can toggle it off, if it is to messie.

@seikur0 what do you think?

**Comment by seikur0** [comment]
I would be fine with a toggle button in the map itself.
