### ISSUE TITLE
[Request] Twitter support

### ISSUE THREAD

**Issue by claimer21** [seikur0/PGO-mapscan-opt#169]
Any chance you're looking at adding support for a twitter bot to notify of rare spawns?   I'd love to set one up in my area.

**Comment by seikur0** [comment]
Ideally I want to integrate PokeAlarm, haven't had time for it yet.

**Comment by nyxdis** [comment]
Integrating PokeAlarm means adding support for PoGoM-style webhooks? Because that would be super simple ([API here](https://github.com/PokemonGoMap/PokemonGo-Map/wiki/Using-Webhooks)) and super awesome.

**Comment by seikur0** [comment]
It's a kind of ugly style to do that in my opinion, I'm not sure, I want that. Why would you send notifications over the local network instead of directly as variable?

**Comment by nyxdis** [comment]
It's actually pretty elegant. That way you can communicate with any application (local or remote, python or any other language) without even changing the code. This makes it extremely extensible and even cross-"platform" in this case since you'd be able to run webhooks that were originally designed for PokemonGo-Map with PGO-mapscan-opt data.

**Comment by seikur0** [comment]
Sure it's good for communicating over different programming languages, but most of the stuff for Pokemon Go is written in python, so that doesn't seem necessary. The bad thing about it is, that only one application can actually receive them at a time, because ports are exclusive.

Wouldn't you just use modules for that normally?

**Comment by nyxdis** [comment]
You can actually run several webhooks without any problem. The port is not hardcoded, so you can run multiple webhooks on different ports. PokemonGo-Map works like this with configurable webhook URLs, you just pass it the address of PokeAlarm and any other webhook you like.
Modules have one disadvantage: you need to touch the original code. If you write a PokeAlarm module, it doesn't magically work, you have to edit main0.py so it makes use of that module. With network communication, you just add the URL to the webhook in your config and done. Also updates to PokeAlarm (or whatever webhook you like) are possible without restarting the map.

**Comment by seikur0** [comment]
I see. Thanks for explaining it to me. I'm semi or three quarters convinced now :D

**Comment by nyxdis** [comment]
The real reason I'm looking forward to this might make this a bit clearer: I'm running a webapp that displays a filterable list of spawnpoints (name+gps), timestamp and pokemon that spawned. Right now I have an upload form where I can upload spawns0.txt. With something like webhooks, I could have a live list and would never have to upload anything.
I'm also writing another app currently that parses spawns0.txt, checks distance to given GPS coordinates (e.g. my home address) and only sends Telegram messages if something spawns near me. This currently doesn't work well because checking changes in spawns0.txt causes a really high cpu load on my RPi3, webhooks would fix that. :)
Hope you're fully convinced now, heh!

**Comment by nyxdis** [comment]
I've implemented [basic webhook support](https://github.com/cmende/PGO-mapscan-opt/tree/webhooks)
It seems to work (only tested against dummy server, not PokeAlarm), but definitely needs tweaking. Probably best to run in a new thread and with a queue. Running out of time for today, but if you want to implement it, it's a start.

Edit: Alternatively, move this a few lines down so it filters by push_ids, but the PokemonGo-Map way is send everything and let the webhook application filter.

**Comment by seikur0** [comment]
I added webhooks and you can now use PokeAlarm, so closed :)

**Comment by claimer21** [comment]
@seikur0 How should the input be in the usersettings file for webhook URL?  I've tried "urls_webhook": http://localhost:4000, and "urls_webhook": [http://localhost:4000], and I'm getting "The settings file is not a valid format, No JSON object could be decoded" when running main0.py

**Comment by seikur0** [comment]
It's

"urls_webhook": ['http://localhost:4000'],

Strings like this are always enclosed in quotes.
