### ISSUE TITLE
Could you add some documentation in your code?

### ISSUE THREAD

**Issue by stam** [seikur0/PGO-mapscan-opt#17]
Hey seikur0, I really like this implementation because it's a pretty accessible codebase.
I still have some questions regarding your implementation
- What exactly is a heartbeat (what does heartbeat()) do?
- What is an ll?
- What does this loop in main() do? 

```
for a in range(1,HEX_NUM+1):
        for i in range(0,a*6):
```
- What does getNeighbors do?

Thanks

**Comment by seikur0** [comment]
- A heartbeat is a request to the niantic server to send back the surrounding informations on the map for a certain position.
- An ll is what I called the LatLng objects, that hold the latitude and longitude for the points at which I'll request the heartbeats.
- That loop calculates these planned heartbeat coordinates. It starts at the center (a=0), then goes downwards and spirals leftwards towards the outside. For each layer a increases by 1. The 6 if cases inside represent the sides of the resulting pseudo hexagon, like the 1st case is the side starting from south towards northeast, then 2nd case means the side connecting to the first one and going towards the north and so on around the center. Look at this picture(numbers unrelated): http://mathworld.wolfram.com/images/eps-gif/MagicHexagon_1000.gif It's going 5,  7,2,4,8,6,1,   3,19,16,...... Each layer has 6 hexes around more, so that's where that 6 comes from: for i in range(0,a*6):
- With each hearbeat you have to send so called s2 cells together with your location and the server will only send you back pokemon locations that are within 100 m range and also are within one of the cells you sent. Use google to find out about them, they are parallelograms close to rectangles depending on the location. GetNeighbors collects the center cell and the 8 cells around it, since a 100 m radius will always be within them. Apparently the real app sends the center cell, the 8 surrounding cell and then for each of the 4 sides 3 more to the outside, which is a circular pattern, so these are the commented lines. You can also take a look at this github page for visualization: (also included in my readme) https://github.com/spezifisch/geoscrape

**Comment by stam** [comment]
Thank you!
