### ISSUE TITLE
[Request] Show Time Left on Notifications

### ISSUE THREAD

**Issue by jRam84** [seikur0/PGO-mapscan-opt#178]
Show time left in the notifications messages. PokeAlarm does this, its really helpful to decide whether to go or ignore a pokemon. 

The current message only gives the time when the pokemon is going to disappear, that is fine but every second matters when a super rare spawns. With Time Left you can guesstimate in a second if you are going to be able to get there on time or not.

![timeleft](https://cloud.githubusercontent.com/assets/20618491/18423069/5f140e90-7856-11e6-8cd7-4961ba831987.png)

**Comment by FrozenSocket** [comment]
Just moved to using notifications again (after my first try caused pushbullet to bootloop my phone because it couldn't process all the notifications fast enough - lesson learned :).
This is such a majorly needed quality of life enhancement - Easy to add ourselves but before @seikur0 tells me to get on with it; I might just do that to help out a very very very little a bit lol.

**Comment by FrozenSocket** [comment]
Closed with #211 ?

**Comment by seikur0** [comment]
Now closed, I tweaked it just now to show seconds as well.

**Comment by FrozenSocket** [comment]
I didn't include the seconds because imo they are irrelevant and it not like the notification can update. But maybe more importantly it causes the 'disappears at' line to wrap onto another second line.

![image](https://cloud.githubusercontent.com/assets/22102429/18615444/3b28b082-7d9f-11e6-9054-27cb22df891b.png)

Personally I'd prefer it without seconds, but it's your call.

**Comment by seikur0** [comment]
I see. I put it back to minutes.

**Comment by FrozenSocket** [comment]
I guess it's different for everyone depending on screen size, I have 5.5" phone.
Maybe we could add something to the config in future that lets everyone format their own.
