### ISSUE TITLE
Best way to map spawnpoints of an island with 500 accounts?

### ISSUE THREAD

**Issue by joshuakoh7** [seikur0/PGO-mapscan-opt#182]
I'm trying to map out the spawn points of an island (about 720km^2). I am sure that the 500 accounts cannot finish the entire area in 15 minutes for the initial spawnpoint mapping and I don't mind it taking a day to progressively map the area by smaller boxes or something. Can I just plug all the accounts under one worker?
Also, I'd like to route all the requests through a round robin chain of proxies so I don't get softbanned on the IP.

**Comment by darkforcesjedi** [comment]
I created a thing on jsfiddle (https://jsfiddle.net/darkforcesjedi/rsrj2cp9/) to help me subdivide my map region into smaller regions (I used radius 13 hex grids and tiled them to cover the regions of interest). My addHexGrid function will add a grid centered at a point with the desired number of grid layers (orientation and tile size match PGO-mapscan-opt). the gridStep function will create a new hex grid adjacent to the grid centered at a point and return the center point of the new grid. All the grid centerpoints are output to the javascript console.

Then I created a script that would create an settings file and run PGO-mapscan-opt, wait for it to produce the spawn point data file, terminate the python instance and repeat for all of the subdivided areas. I used 12 accounts to scan 15 grids made of 13 layers each.

The number of tiles in a grid with "L" layers is N=3_L_(L+1)+1. I have found that 1 account can typically scan 4.6 tiles per minute. Divide the number of tiles by 4.6 \* Time, where Time is the amount of time you allow to complete a single scan (I used 10 minutes instead of 15 to determine that 13 layers required 12 accounts and allow some margin so no scans would go for more than 15 minutes.) e.g. you could do 20 layers with 28 accounts or 24 layers with 40 accounts. You can create multiple instances of PGO-mapscan-opt by extracting it into different directories and running them in parallel.

Once you have all the spawn point files, you can collect them in the same folder and use the spawnfix.py file to combine them into a single file. In intelligent scan mode, one account can scan about 300 spawn points per hour. Divide the number of spawn points by 300 to determine how many accounts you need to scan the combined area. I have 20,900 spawn points in my area so I need about 70 accounts to scan the whole thing.

Rename the output from spawnfix.py to LATITUDE_LONGITUDE_LAYERS_70.0.json (replace LATITUDE, LONGITUDE, LAYERS with the actual values from your new input file, they can be any valid values as long as they match exactly). When you run main0.py it will look for a spawn point file named with the same latitude, longitude, and range as your input file and if it finds that it will use the file instead of a traditional hex grid scan.

**Comment by seikur0** [comment]
I'm currently also working on something to make large areas scannable very easily, based on google s2 cells. So if you can wait until tomorrow or the day after that.. ;)

**Comment by joshuakoh7** [comment]
Let's hope Niantic hasn't pushed the forced update by then :P

**Comment by darkforcesjedi** [comment]
Also, 500 accounts should be far more than you need to accomplish this. When I finish adding all the area to my map that I am interested in, it will be about 600 km^2. I expect to have around 40,000 spawn points total. Depending on how urban your area is you may have 60,000 to 80,000 spawn points in your area. 200-300 accounts should be sufficient to handle it once you have your learning file complete. The challenge will be running that many accounts without getting IP bans. I got an IP ban from running 60 accounts, but I ran 50 accounts for a week with no issue.

**Comment by seikur0** [comment]
I can use about 140 accounts without them getting softbanned as long as they stay inside the confines of a r30 pseudo-hex surrounded by 6 other r30 pseudo-hexes.

**Comment by cheezy64** [comment]
@seikur0 did the feature to make large scannable areas simple ever get implemented??  If so, can you point to the documentation (if it exists)

**Comment by seikur0** [comment]
I finished that part yesterday and it's working well. I'll add in the auto-time delay feature and some small details and documentation :/ and then I should be done with it and can put it out.

**Comment by seikur0** [comment]
Implemented and closed.

**Comment by Coalado** [comment]
Can you give me some guidance how to use this now "scan Large area" feature?

**Comment by seikur0** [comment]
Consult the [wiki](https://github.com/seikur0/PGO-mapscan-opt/wiki/Plan-Mode)
