### ISSUE TITLE
[Request] Button to find your location on the webpage

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#189]
Linked to my previous request, when I'm accessing the website externally via a mobile device it would be fantastic to have the ability to just click a 'target' button (Like Google Maps - maybe built into the API?) and pan to my location with the page requesting my location information from the device GPS.

Additionally if this information was periodically requested automatically so you don't have to keep clicking and scrolling every few seconds when your moving all even better :)

**Comment by seikur0** [comment]
Well you're in luck, since that button is already there, you just have to start using it ;) I don't like the automatic requests though, because of bandwidth and background battery usage. That button isn't working with the newest Chrome though and I can't do anything about it. (https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only?hl=en) 

Chrome decided to "protect" users by removing the possibility to get the location for non https websites. Pretty stupid, if you ask me.
