### ISSUE TITLE
"Strange" 60 min Spawnpoint

### ISSUE THREAD

**Issue by Coalado** [seikur0/PGO-mapscan-opt#195]
Please check this point:
  {
   "spawntime": 2088683,
   "pausetime": 3600000,
   "lat": 49.41676662789082,
   "lng": 10.934214552392646,
   "type": 104,
   "id": 4921851635589
  },
According to my Spawnfile, this is type 104 (1x60)
However, the scanner only shows 1 spawn  in Quater 1 (0-15 min)
I checked this point physically (went there). It IS indeed a 1x60.
So why does the scanner show only a 15 minute spawn?

It seems like several 104er points have such problems.

**Comment by seikur0** [comment]
"pausetime": 3600000 is the issue here. That pausetime, is it from a scan with the new algorithm? You can manually set it to 0, which will fix it, but I'd like to look into how that value came into the learning file.

**Comment by Coalado** [comment]
can you explain the pausetime value?

the spawnoint has been created on 11.9 or earlier.
I more recent scan results in this:

  {
   "spawntime": 2006633,
   "pausetime": 573459,
   "lat": 49.41676662789082,
   "lng": 10.934214552392646,
   "type": 104,
   "id": 4921851635589
  },

**Comment by ilovetobowl** [comment]
I did a one hour, 20s-interval scan specifically for one 1x60 spawnpoint that's isolated from everything else. I set range=0 so it's  the only spawn point to scan in that entire hour. I ended up also with a 360000 pause time after the 1-hour learning.

**Comment by seikur0** [comment]
A pausetime like  573459 would be the normal case, so about 10 minutes time, in which you don't know, if the last pokemon is still there or the new one is there already. For now you can fix this by setting it to "pausetime": 0. That means instead of showing no pokemon for the last ~10 minutes, the old pokemon is still being shown as present, while the next one could actually be there already.

I fixed it just now, it was a bug indeed.

1x60 points are kind of annoying, because you can't determine their exact spawn time..

**Comment by Coalado** [comment]
So 
"spawntime": 2006633,
"pausetime": 573459,

means that the pokemon is there at least from 2006633 to 2006633+(60_60_1000)-573459 and maybe even longer?

**Comment by seikur0** [comment]
2006633 to 2006633 + (3600000 - 573459), with the full 3600000 ms meaning an hour, and the pausetime reducing this by an uncertainty of 573459 ms, so about 10 minutes.

There is always a pokemon at a 1x60 point, this pausetime just says, that it can't be determined exactly without scanning it in a lower interval. Some of that pausetime still belongs to the pokemon before and the rest to the pokemon after that and since 1 hour reduced to 45+ min is still pretty long, I'm basically not showing a pokemon on the map in that pausetime rather than a wrong one.

**Comment by mcdsojcd** [comment]
Hi, I have also three of them in the .json file, should I get the latest main0.py and rescan these points?

**Comment by seikur0** [comment]
No for you it's a totally different thing. Irony.. (Sry, hard day :D )
