### ISSUE TITLE
Exception stopping scan after trying to log in with banned account

### ISSUE THREAD

**Issue by rafsawicki** [seikur0/PGO-mapscan-opt#210]
I've got one of my workers banned and scanning froze because of this. I've checked why and it's because a method `login_ptc` expects that a response body is always a valid json, even in error handler.

Response I'm getting when trying to log in:
`error=invalid_grant`

Traceback:
`Traceback (most recent call last):`
`File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner`
`self.run()`
`File "main0.py", line 1250, in run`
`do_login(self.account)`
`File "main0.py", line 484, in do_login`
`login_ptc(account)`
`File "main0.py", line 454, in login_ptc`
`answer = json.loads(r.content)`
`File "C:\Python27\lib\json\__init__.py", line 339, in loads`
`return _default_decoder.decode(s)`
`File "C:\Python27\lib\json\decoder.py", line 364, in decode`
`obj, end = self.raw_decode(s, idx=_w(s, 0).end())`
`File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode`
`raise ValueError("No JSON object could be decoded")`
`ValueError: No JSON object could be decoded`

**Comment by seikur0** [comment]
Can you give me the account info? Well it is a valid json for the 3 cases, that I catch. Damm why are they so arbitrary about their responses.. They should fire their web designer.

**Comment by rafsawicki** [comment]
I've checked this account one more time before sending it to you, after having it out of workers pool for a few hours and it logged in without issue. Yesterday I had this error every time I tried to log in on both, my remote server and local machine. I guess that it was either some sort of temporary ban or simply an error on their side. If anything like that happens again I'll let you know.

**Comment by seikur0** [comment]
Yeah but I'll still catch that error, gotta catch them all ;)

**Comment by drtakhs** [comment]
Hey, i just got the same error some hours ago and the scan process continued normally after spitting the above errors in the cmd... Then i decided to close and restart the whole thing. I got the same error while the accounts were being connected... Then i closed and reopened it once again, and it worked without any errors what so ever... That makes me think that it's an issue on their side, not a ban. (i wasn't updated to latest version that's why i saw this message, i know it's fixed, but i thought i'd share some insight)

**Comment by seikur0** [comment]
They're not winning any prices for server stability any time soon haha
