### ISSUE TITLE
telebotsettings.json help

### ISSUE THREAD

**Issue by ftuttle5** [seikur0/PGO-mapscan-opt#269]
Is this file necessary for telegram notifications, or can I just modify usersettings.json? Looking at telebotsettings.json, some of the lines confuse me. Especially this one:

"_comment" : "Radius set by default on receiving location, radius step for each time they make it bigger or smaller and maximum allowed radius",

Could you clarify on what this means and if it is necessary?

**Comment by seikur0** [comment]
It's the notification radius, as standard you get notifications from pokemon up to a distance of 300 m and you have the possibility to set it inside the bot in steps of 100 m with 10000 m being the max. I'm not sure, how useful maximum allowed radius is, because from my understanding you can still get every notification, if you don't set the location in the first place. This'll be revised.
