### ISSUE TITLE
local Varible "f" not ref before assignment

### ISSUE THREAD

**Issue by garyandtaz321** [seikur0/PGO-mapscan-opt#3]
Apon execution I get the errors:
File "main0.py", line 541 in <module>
main()
File main0.py line 495 in main
f.close()
UnboundLocalError: local variable 'F' reference before assignment.

Any ideas?

**Comment by garyandtaz321** [comment]
Running Python 2.7.6 if that makes a difference

**Comment by seikur0** [comment]
Can you update your files and see if it still gives you an error? I'm not sure if that makes a difference, I have Python 2.7.12 running though.

**Comment by garyandtaz321** [comment]
Ok, one minute

**Comment by jeppybro** [comment]
I was running it just fine and all was well. Copied everything + updated in a subfolder for a different location and started getting this error. Running as sudo (prob not smart) allows it to work, though? 

Updated files with same issue.

**Comment by seikur0** [comment]
Seems to me like you just don't have write file access as normal user in that subfolder (read file works though, since it reads the language file before. So it can't create f, which throws an error, that error is being caught, because it's in the try routine and it tries to execute line 495, which then crashes the program, because it couldn't create f in the first place.

Okay I'll close this issue, I'm pretty sure that's what happened. When I update the main0.py, I'll put in a check if f exists, so I can catch that possibility and give a better error message.
