### ISSUE TITLE
Scanning different areas or scanning a big hexagon 

### ISSUE THREAD

**Issue by ferazambuja** [seikur0/PGO-mapscan-opt#32]
Can you please clarify this parameters a bit more:
`"_comment2": "If unique_coordinates is set to false, profile coordinates will be overwritten with standard_coordinates.",
  "unique_coordinates": false,
` 
and
`"_comment5": "Set to true to overwrite the coordinates for id 1 to 6 to scan around the id 0 pseudo-hexagon.",
  "centralscan": false,`

Situation 1: I have multiple accounts, and I want to scan a continuous area. 
-What are the settings? "false","false"
-Should I leave the workers with lat and lng as "0" on the profiles settings? Also for id0?
-Should I expand the radius?
-Or it "attaches" around a new hex to the side of the id 0 one? ie: id 1 top left, id 2 top top, id 3 top right...

Situation 2: My area has some gaps or I just want to place my workers far away from each other.
-What are the settings? "true","false"
-What should I type in the standard coordinates? Is this the ones the browser will lock at the start?
-Should I type the lat and lng for each one on their profiles?
-Do I need to run multiple instances of the script for each worker? main0.py -id 0, main0.py -id 1 ,main0.py -id 2...

I do know some of this answers, however, would be good to have them better explain on the readme. I could write a step by step for this if you want.

Best

**Comment by seikur0** [comment]
Situation 1: You can put centralscan to "true", unique_coordinates doesn't matter, if you do, then 7 accounts from id0 to id6 will be used, the coordinates then will be taken from "standard_coordinates", so no need to set them in the accounts. You can probably shrink the radius with that setting. It attaches as you said.

However you can also use the 6 accounts or less of them without centralscan, then you need to sync them by manually starting them at certain time intervals and also setting their scanintervals to a greater number than they need for that scan. Example: you set -r to the area you want, try it, scantime around 19 min, you want the map to be updated with data every 5 minutes, you choose 20 min as scan interval and start the workers one after another in a 5 minute rhythm. centralscan would be "false", unique_coordinates also.

Situation 2: 
Since every scanner should be on unique coordinates, you set that to "true". centralscan of course not, remember that overwrites the coordinates.
The browser will lock to the standard_coordinates if unique coordinates is off, otherwise to the coordinates of the id0 profile.
You need an instance for each new worker/id.

I you write a good step by step, I'll link it in the readme :)
