### ISSUE TITLE
Multiple Accounts Question

### ISSUE THREAD

**Issue by ghost** [seikur0/PGO-mapscan-opt#75]
So this is a simple question, not sure if this is the best place to ask it or not.

I'm trying to figure out the best way to setup everything as fast and efficient as possible. I read through the FAQ and still a bit confused.

I'm trying to use several accounts, and I understand that you have to add multiple accounts to the JSON under the same ID. Am i supposed to manually type in each coordinate a certain distance away, or does the algorithm use the multiple accounts starting all in the same location?

Thanks

**Comment by DanHazard** [comment]
You have two options:

If you want all the workers to help out together, over single area (so like range of 10 around specific lat/long) then all you need to do is fill out the lat/long for the first worker, and make sure they all have the same id's

If you want to scan multiple different area's and split yr workers up into groups, then you need to adjust the id's of the workers, and then the lat/long of the workers going to each area.

So if I wanted to scan two areas of r10 in my city, rather than one area of r20 (maybe they are a few miles apart) then I would take 5 of my workers, name them id 0 and give the first one in that group a lat/long, and then I would take the other 5 of my workers, give them all id 1 and set the first worker in that group to have the other lat/long

Hope that helps.

**Comment by ghost** [comment]
@DanHazard Awesome thank you so much!
