### ISSUE TITLE
Exception, once off on a run with banned accounts

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#91]
Running current commit as of https://github.com/seikur0/PGO-mapscan-opt/commit/99257acacd705d21dde2202c3f6728edee17983b

File "c:\mapscanopt\main0.py", line 917, in run
    empty_ll[all_ll.index(this_ll)] = 0
ValueError: LatLng: -33.793627178,151.097982988 is not in list

Kept scanning after the exception.
Wasn't repeatable on relaunch with same accounts.
I've since removed those accounts and haven't had it come up since.
Just thought you should know.

**Comment by seikur0** [comment]
Okay fixed. When accounts are banned, the location they currently have is put back onto the scan queue, so it won't be skipped. But instead of the location, it's a pointer to the LatLng object, I didn't think that through and created a new one from the coordinates instead of using the correct already existing one.
